#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

export HF_HOME="${HF_HOME:-$SCRIPT_DIR/.hf_cache}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$HF_HOME}"
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-$HF_HOME/datasets}"
export HF_ALLOW_CODE_EVAL=1
export HF_DATASETS_TRUST_REMOTE_CODE=true
mkdir -p "$HF_HOME" "$HF_DATASETS_CACHE"

TASK="${TASK:-gsm8k}"
MODEL_PATH="${MODEL_PATH:-GSAI-ML/LLaDA-8B-Instruct}"
LIMIT="${LIMIT:-}"
GEN_LENGTH="${GEN_LENGTH:-128}"
STEPS="${STEPS:-$GEN_LENGTH}"
BLOCK_LENGTH="${BLOCK_LENGTH:-32}"

CORA_NUM_GROUPS="${CORA_NUM_GROUPS:-4}"
CORA_CORE_RATIO="${CORA_CORE_RATIO:-0.5}"
CORA_ACTIVE_RATIO="${CORA_ACTIVE_RATIO:-0.7}"
CORA_ACTIVE_RATIO_FINAL="${CORA_ACTIVE_RATIO_FINAL:-0.45}"
CORA_BUDGET_SCHEDULE="${CORA_BUDGET_SCHEDULE:-cosine}"
CORA_ALPHA="${CORA_ALPHA:-0.3}"
CORA_DEPENDENCY_TOPK="${CORA_DEPENDENCY_TOPK:-16}"
CORA_CHANNEL_ORDERING="${CORA_CHANNEL_ORDERING:-activation}"
CORA_EXTRA_COMMIT="${CORA_EXTRA_COMMIT:-true}"
CORA_ROUTING_MODE="${CORA_ROUTING_MODE:-disabled}"
CORA_ORDER_CHANNELS="${CORA_ORDER_CHANNELS:-false}"
CORA_FAST_ACCEPT="${CORA_FAST_ACCEPT:-true}"
CORA_ACCEPT_CONFIDENCE_THRESHOLD="${CORA_ACCEPT_CONFIDENCE_THRESHOLD:-0.90}"
CORA_ACCEPT_STABILITY_STEPS="${CORA_ACCEPT_STABILITY_STEPS:-1}"
CORA_EOT="${CORA_EOT:-true}"
CORA_EOT_CONFIDENCE_THRESHOLD="${CORA_EOT_CONFIDENCE_THRESHOLD:-0.50}"
CORA_RESIDUAL_ACCEPT="${CORA_RESIDUAL_ACCEPT:-false}"
CORA_RESIDUAL_THRESHOLD="${CORA_RESIDUAL_THRESHOLD:-0.0}"
CORA_DRIFT_TOPK="${CORA_DRIFT_TOPK:-8}"
CORA_RESIDUAL_BETA="${CORA_RESIDUAL_BETA:-1.0}"
CORA_RESIDUAL_GAMMA="${CORA_RESIDUAL_GAMMA:-1.0}"
CORA_PERSISTENCE_TEMPERATURE="${CORA_PERSISTENCE_TEMPERATURE:-2.0}"

mkdir -p "output/eval_results/${TASK}"

MODEL_ARGS="model_path=${MODEL_PATH},gen_length=${GEN_LENGTH},steps=${STEPS},block_length=${BLOCK_LENGTH},method=CORA,cora_routing_mode=${CORA_ROUTING_MODE},cora_num_groups=${CORA_NUM_GROUPS},cora_core_ratio=${CORA_CORE_RATIO},cora_active_ratio=${CORA_ACTIVE_RATIO},cora_active_ratio_final=${CORA_ACTIVE_RATIO_FINAL},cora_budget_schedule=${CORA_BUDGET_SCHEDULE},cora_alpha=${CORA_ALPHA},cora_dependency_topk=${CORA_DEPENDENCY_TOPK},cora_order_channels=${CORA_ORDER_CHANNELS},cora_channel_ordering=${CORA_CHANNEL_ORDERING},cora_extra_commit=${CORA_EXTRA_COMMIT},cora_fast_accept=${CORA_FAST_ACCEPT},cora_accept_confidence_threshold=${CORA_ACCEPT_CONFIDENCE_THRESHOLD},cora_accept_stability_steps=${CORA_ACCEPT_STABILITY_STEPS},cora_eot=${CORA_EOT},cora_eot_confidence_threshold=${CORA_EOT_CONFIDENCE_THRESHOLD},cora_residual_accept=${CORA_RESIDUAL_ACCEPT},cora_residual_threshold=${CORA_RESIDUAL_THRESHOLD},cora_drift_topk=${CORA_DRIFT_TOPK},cora_residual_beta=${CORA_RESIDUAL_BETA},cora_residual_gamma=${CORA_RESIDUAL_GAMMA},cora_persistence_temperature=${CORA_PERSISTENCE_TEMPERATURE}"

echo "Running CORA-Diff"
echo "TASK=${TASK}"
echo "LIMIT=${LIMIT:-full}"
echo "MODEL_PATH=${MODEL_PATH}"
echo "MODEL_ARGS=${MODEL_ARGS}"

LIMIT_ARGS=()
if [ -n "$LIMIT" ]; then
  LIMIT_ARGS=(--limit "$LIMIT")
fi

accelerate launch eval_llada.py \
  --tasks "$TASK" \
  "${LIMIT_ARGS[@]}" \
  --model llada_dist \
  --confirm_run_unsafe_code \
  --model_args "$MODEL_ARGS" \
  2>&1 | tee "output/eval_results/${TASK}/eval_CORA_${GEN_LENGTH}.log"
